# Working on Real-Time Project with Python on 'Udemy Courses Dataset'

# UDEMY COURSES DATASET

-----

This dataset contains all course data for all subjects.

We will analyze this data using the Pandas Library.

Here, the quesitons are given for the practice and learning purpose.

 ----

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Datasets/Project+7+-+Udemy+Dataset.csv')

In [3]:
df.head()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments

In [4]:
df.shape

(3682, 11)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3682 entries, 0 to 3681
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3682 non-null   int64
 1   course_title         3682 non-null   object
 2   is_paid              3682 non-null   bool
 3   price                3682 non-null   object
 4   num_subscribers      3682 non-null   int64
 5   num_reviews          3682 non-null   int64
 6   num_lectures         3682 non-null   int64
 7   level                3682 non-null   object
 8   content_duration     3682 non-null   object
 9   published_timestamp  3682 non-null   object
 10  subject              3682 non-null   object
dtypes: bool(1), int64(4), object(6)
memory usage: 291.4+ KB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
course_id,3682.0,676612.106192,343635.483126,8324.0,407843.00,688558.0,961751.50,1282064.0
num_subscribers,3682.0,3194.230310,9499.378361,0.0,110.25,911.5,2540.25,268923.0
num_reviews,3682.0,156.093156,934.957204,0.0,4.00,18.0,67.00,27445.0
num_lectures,3682.0,40.065182,50.373299,0.0,15.00,25.0,45.00,779.0

In [7]:
df.isna().sum()

course_id              0
course_title           0
is_paid                0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
content_duration       0
published_timestamp    0
subject                0
dtype: int64

In [8]:
df.select_dtypes('object').columns.tolist()

['course_title',
 'price',
 'level',
 'content_duration',
 'published_timestamp',
 'subject']

In [9]:
df.select_dtypes('int').columns.tolist()

['course_id', 'num_subscribers', 'num_reviews', 'num_lectures']

### 1. What are all different subjects for which Udemy is offering courses ?

In [10]:
df.columns.tolist()

['course_id',
 'course_title',
 'is_paid',
 'price',
 'num_subscribers',
 'num_reviews',
 'num_lectures',
 'level',
 'content_duration',
 'published_timestamp',
 'subject']

In [11]:
df.subject.unique()

array(['Musical Instruments', 'Business Finance', 'Graphic Design',
       'Web Development'], dtype=object)

### 2. Which subject has the maximum number of courses.

In [12]:
df.subject.value_counts().reset_index().rename(columns={'index': 'subject', 'subject':'Count'}).sort_values('Count', ascending=False)

               subject  Count
0      Web Development   1200
1     Business Finance   1199
2  Musical Instruments    680
3       Graphic Design    603

### 3. Show all the courses which are Free of Cost.

In [13]:
df.head(3)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments

In [14]:
df[(df.is_paid == False) | (df.price == 'Free')]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
41,286070,5 lecciones que todo guitarrista debe tomar,False,Free,4452,263,14,Beginner Level,1 hour,2014-08-23T05:08:14Z,Musical Instruments
49,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",False,Free,4529,193,7,Beginner Level,36 mins,2015-12-21T18:50:50Z,Musical Instruments
57,955914,A beginner`s guide to fingerpicking and strumm...,False,Free,3481,29,20,Beginner Level,2 hours,2016-09-13T21:51:59Z,Musical Instruments
67,270976,A how to guide in HTML,False,Free,7318,205,8,Beginner Level,35 mins,2014-08-10T20:19:10Z,Web Development
74,1214144,¡Triunfar en La Bolsa de Valores No Requiere d...,False,Free,338,7,6,Beginner Level,1 hour,2017-05-30T14:30:12Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3620,552598,WordPress in under an hour - Create/manage you...,False,Free,6474,86,15,All Levels,1 hour,2015-07-15T00:21:56Z,Web Development
3638,1068590,Wordpress Website Mastery 2017,False,Free,5181,64,22,Beginner Level,2.5 hours,2017-01-18T17:01:40Z,Web Development
3652,752706,Write quicker HTML5 and CSS 3; productivity ha...,False,Free,13016,286,15,All Levels,1.5 hours,2016-03-03T17:45:31Z,Web Development
3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29T00:29:36Z,Musical Instruments
3680,1225194,Zoho Books Gestion Financière d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance

In [15]:
df[(df.is_paid == False) | (df.price == 'Free')].shape[0]

310

### 4. Show all the courses which are Paid.

In [16]:
df[df.is_paid == True]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26T20:48:48Z,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [17]:
df[df.is_paid == True].shape[0]

3372

### 5. Which are Top Selling Courses ?

In [18]:
df.head(3)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments

In [19]:
df.sort_values('num_subscribers', ascending=False)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...
2290,1223240,Learn Pirates of the Caribbean by Ear on the P...,True,20,0,0,6,All Levels,32 mins,2017-05-22T17:14:43Z,Musical Instruments
1267,1258666,Financial Statement Auditing Cycles,True,50,0,0,9,Intermediate Level,2 hours,2017-06-29T23:20:10Z,Business Finance
2070,1215926,Kickstarter success in 5 easy steps,True,20,0,0,12,All Levels,31 mins,2017-05-16T14:55:28Z,Business Finance
1931,1247992,Introduction to Project Management for Finance...,True,50,0,0,9,Beginner Level,2 hours,2017-07-03T21:40:32Z,Business Finance
3165,1087466,Stop Creditors from Harassing you and Avoid Ba...,True,20,0,0,7,Beginner Level,37 mins,2017-02-02T16:22:37Z,Business Finance

In [20]:
df.sort_values('num_subscribers', ascending=False).head(10)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
1388,19421,Free Beginner Electric Guitar Lessons,False,Free,101154,1042,95,Beginner Level,4.5 hours,2012-06-15T17:00:33Z,Musical Instruments
3556,473160,Web Design for Web Developers: Build Beautiful...,False,Free,98867,6512,20,All Levels,3 hours,2015-04-13T18:29:47Z,Web Development
2233,94430,Learn Javascript & JQuery From Scratch,True,30,84897,2685,10,All Levels,2 hours,2013-10-10T15:19:29Z,Web Development
2886,130064,Practical PHP: Master the Basics and Code Dyna...,False,Free,83737,4598,45,All Levels,6.5 hours,2014-07-19T03:02:05Z,Web Development
2034,364426,JavaScript: Understanding the Weird Parts,True,175,79612,16976,85,All Levels,11.5 hours,2015-03-12T23:19:54Z,Web Development

### 6. Which are Least Selling Courses ?

In [21]:
df.sort_values('num_subscribers', ascending=True)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
649,1233314,Building a Balanced Scorecard,True,50,0,0,11,Intermediate Level,2 hours,2017-07-03T21:38:22Z,Business Finance
3259,1232282,The Cash Flow Statement - An Introduction,True,50,0,0,10,Beginner Level,1.5 hours,2017-06-28T16:05:51Z,Business Finance
3261,1275872,The Complete Adobe Spark Course,True,150,0,0,29,All Levels,2 hours,2017-07-03T17:39:57Z,Graphic Design
910,726314,Create Beautiful Image Maps for Your Website,True,20,0,0,8,Intermediate Level,37 mins,2016-01-18T17:56:36Z,Graphic Design
3328,715476,The Cuckoo Strategy to get European Funding,True,160,0,0,6,All Levels,1 hour,2016-01-06T02:38:23Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development

In [22]:
df.sort_values('num_subscribers', ascending=True).head(10)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
649,1233314,Building a Balanced Scorecard,True,50,0,0,11,Intermediate Level,2 hours,2017-07-03T21:38:22Z,Business Finance
3259,1232282,The Cash Flow Statement - An Introduction,True,50,0,0,10,Beginner Level,1.5 hours,2017-06-28T16:05:51Z,Business Finance
3261,1275872,The Complete Adobe Spark Course,True,150,0,0,29,All Levels,2 hours,2017-07-03T17:39:57Z,Graphic Design
910,726314,Create Beautiful Image Maps for Your Website,True,20,0,0,8,Intermediate Level,37 mins,2016-01-18T17:56:36Z,Graphic Design
3328,715476,The Cuckoo Strategy to get European Funding,True,160,0,0,6,All Levels,1 hour,2016-01-06T02:38:23Z,Business Finance
1325,1187084,Forex how traders beat the markest with little...,True,100,0,0,16,All Levels,1 hour,2017-07-06T21:16:13Z,Business Finance
2596,185526,MicroStation - Células,True,20,0,0,9,Beginner Level,37 mins,2014-04-15T21:48:55Z,Graphic Design
2597,185526,MicroStation - Células,True,20,0,0,9,Beginner Level,37 mins,2014-04-15T21:48:55Z,Graphic Design
848,1232390,Corporate Ethics,True,100,0,0,13,Beginner Level,3.5 hours,2017-07-03T21:39:13Z,Business Finance
2900,995384,Professional Business Logo Design Using Free O...,True,20,0,0,5,All Levels,37 mins,2016-10-31T16:09:48Z,Graphic Design

### 7. Show all courses of Graphic Design where the price is below 100 ?

In [23]:
df.head(3)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments

In [24]:
filtered = df[(df.subject == 'Graphic Design') & (df.is_paid == True)]
filtered

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
8,206592,:::Beginners Guide To Creating Amazing Images ...,True,25,72,5,17,Beginner Level,1 hour,2014-04-29T19:50:31Z,Graphic Design
20,1165268,15 Motion Graphic Elements in After Effect (S...,True,30,8,0,20,Intermediate Level,3 hours,2017-04-11T04:27:34Z,Graphic Design
35,1164876,3DS MAX - Learn 3Ds MAX tutorial for Beginners...,True,20,785,2,29,All Levels,4.5 hours,2017-04-18T16:45:59Z,Graphic Design
39,599652,48 Logo Designs and Techniques,True,20,113,9,48,All Levels,9 hours,2015-09-15T00:23:14Z,Graphic Design
47,1269190,7 Secrets To Designing In Black and White,True,100,1000,1,12,All Levels,1.5 hours,2017-06-27T19:55:18Z,Graphic Design
...,...,...,...,...,...,...,...,...,...,...,...
3588,1131780,"Whiteboard Animation, Beginner To Expert - In ...",True,20,1343,25,16,All Levels,1 hour,2017-03-14T20:52:30Z,Graphic Design
3594,908664,Word Swag : Create Stunning Images with the Wo...,True,100,2416,19,14,All Levels,1 hour,2016-08-09T17:56:53Z,Graphic Design
3639,1122306,Wordpress: Comment utiliser le thème FABLE,True,20,1,0,10,Beginner Level,39 mins,2017-03-07T16:53:27Z,Graphic Design
3671,144222,"YOU can Draw, Shade and Paint a Mixed Media Gi...",True,30,1249,44,19,Beginner Level,3 hours,2014-01-28T02:30:26Z,Graphic Design
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [25]:
filtered.dtypes

course_id               int64
course_title           object
is_paid                  bool
price                  object
num_subscribers         int64
num_reviews             int64
num_lectures            int64
level                  object
content_duration       object
published_timestamp    object
subject                object
dtype: object

In [26]:
filtered = filtered.astype({'price':'int'})

In [27]:
filtered.dtypes

course_id               int64
course_title           object
is_paid                  bool
price                   int32
num_subscribers         int64
num_reviews             int64
num_lectures            int64
level                  object
content_duration       object
published_timestamp    object
subject                object
dtype: object

In [28]:
filtered.shape

(568, 11)

In [29]:
final_df = filtered[filtered.price < 100]
final_df

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
8,206592,:::Beginners Guide To Creating Amazing Images ...,True,25,72,5,17,Beginner Level,1 hour,2014-04-29T19:50:31Z,Graphic Design
20,1165268,15 Motion Graphic Elements in After Effect (S...,True,30,8,0,20,Intermediate Level,3 hours,2017-04-11T04:27:34Z,Graphic Design
35,1164876,3DS MAX - Learn 3Ds MAX tutorial for Beginners...,True,20,785,2,29,All Levels,4.5 hours,2017-04-18T16:45:59Z,Graphic Design
39,599652,48 Logo Designs and Techniques,True,20,113,9,48,All Levels,9 hours,2015-09-15T00:23:14Z,Graphic Design
52,794036,8 Stunden professionelles Cinema 4D Training,True,50,18,1,38,All Levels,8.5 hours,2016-03-22T20:51:28Z,Graphic Design
...,...,...,...,...,...,...,...,...,...,...,...
3568,133968,Web Elements Design With Photoshop,True,45,5072,38,44,All Levels,5 hours,2014-10-21T19:18:12Z,Graphic Design
3588,1131780,"Whiteboard Animation, Beginner To Expert - In ...",True,20,1343,25,16,All Levels,1 hour,2017-03-14T20:52:30Z,Graphic Design
3639,1122306,Wordpress: Comment utiliser le thème FABLE,True,20,1,0,10,Beginner Level,39 mins,2017-03-07T16:53:27Z,Graphic Design
3671,144222,"YOU can Draw, Shade and Paint a Mixed Media Gi...",True,30,1249,44,19,Beginner Level,3 hours,2014-01-28T02:30:26Z,Graphic Design
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [30]:
final_df.shape

(450, 11)

In [31]:
free_graphic = df[(df.subject == 'Graphic Design') & (df.is_paid == False)]
free_graphic

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
161,733878,Adobe Illustrator Course in Urdu Basics Level ...,False,Free,1433,57,8,Beginner Level,1 hour,2016-01-19T17:22:59Z,Graphic Design
175,723818,Adobe Indesign CC Başlangıç,False,Free,637,21,22,Beginner Level,2.5 hours,2016-01-14T18:52:21Z,Graphic Design
319,896742,Aprenda Modelagem 3D com o 123D Design,False,Free,334,26,27,Beginner Level,1 hour,2016-07-07T21:15:34Z,Graphic Design
384,1249378,AutoCAD Course - Learn Online AutoCAD in Urdu ...,False,Free,105,2,22,All Levels,2 hours,2017-06-13T17:32:48Z,Graphic Design
683,1261122,画像加工の初心者でも「１日」で初歩を覚えられる無料講座,False,Free,21,0,18,Beginner Level,1 hour,2017-06-22T15:01:32Z,Graphic Design
684,1185535,Cómo crear maquetas con Adobe XD,False,Free,217,2,21,Beginner Level,3 hours,2017-05-28T16:17:36Z,Graphic Design
705,809216,Canva: Design Album Cover Artwork in Minutes -...,False,Free,3103,42,11,Beginner Level,40 mins,2016-04-07T23:57:25Z,Graphic Design
836,902300,Convert Image to Vector in Adobe illustrator,False,Free,3251,158,13,Intermediate Level,31 mins,2016-07-13T16:57:42Z,Graphic Design
878,650720,Creare un logo con Adobe Illustrator,False,Free,1447,121,13,All Levels,1 hour,2015-10-29T00:10:41Z,Graphic Design
928,874656,Create Stunning Infographics to Share your Ideas,False,Free,5175,470,7,Beginner Level,30 mins,2016-08-14T22:04:11Z,Graphic Design
1024,1181578,Deinen Roman setzen mit PagePlus in 10 einfach...,False,Free,69,6,25,All Levels,3.5 hours,2017-04-24T16:44:12Z,Graphic Design
1056,901082,Digital Art in Adobe Illustrator CC: Angry Bir...,False,Free,3108,27,28,Beginner Level,2.5 hours,2016-08-12T17:34:45Z,Graphic Design
1095,525446,Draw a Kitten,False,Free,3812,68,11,All Levels,1.5 hours,2015-06-12T18:37:40Z,Graphic Design
1096,755680,Draw a realistic Fantail using pencil,False,Free,6754,109,20,All Levels,1 hour,2016-02-11T22:05:05Z,Graphic Design
1217,609642,Ferramentas Visuais,False,Free,817,42,18,Beginner Level,5 hours,2015-10-09T23:42:33Z,Graphic Design
1218,17349,Figure Drawing From Life Using The Reilly Tech...,False,Free,47811,1041,22,All Levels,2.5 hours,2012-05-09T18:14:57Z,Graphic Design
1465,660876,Graphic Design - An Overview of the Field,False,Free,23229,2215,12,Beginner Level,1 hour,2015-11-09T19:10:57Z,Graphic Design
1613,930416,How to design a business card on Photoshop (fo...,False,Free,5086,197,12,Beginner Level,1 hour,2016-08-27T19:02:40Z,Graphic Design
1618,1132572,How to Design an Awesome Letterhead in Adobe I...,False,Free,4776,115,18,All Levels,34 mins,2017-03-03T03:20:22Z,Graphic Design
1709,1156778,How to stylize your photos in Photoshop with c...,False,Free,3512,58,17,Beginner Level,1.5 hours,2017-03-30T16:26:36Z,Graphic Design
1787,590794,Illustrator Quick Tip：10分でKawaiiカメレオンを描こう,False,Free,381,24,7,All Levels,36 mins,2015-08-31T20:52:45Z,Graphic Design
2157,1260674,Learn Comic Book Color Flatting! (Coloring Ass...,False,Free,946,3,6,Beginner Level,40 mins,2017-06-20T17:57:00Z,Graphic Design
2231,627782,Learn Illustrator By Recreating Top 3 Logos - ...,False,Free,8786,245,11,Beginner Level,1 hour,2015-10-04T19:36:34Z,Graphic Design
2352,22445,Learn to Design a Letterhead - A Beginners Course,False,Free,24687,423,13,All Levels,44 mins,2012-10-10T23:34:55Z,Graphic Design
2498,1047508,Make yourself a Santa Claus: Photoshop Manipul...,False,Free,2665,20,8,All Levels,34 mins,2016-12-22T17:10:35Z,Graphic Design
2621,787340,Most Wanted Flat Design Techniques #1: Desert ...,False,Free,4294,143,15,Intermediate Level,1 hour,2016-03-17T18:15:21Z,Graphic Design
2707,1226518,Photoshop & Illustrator CC Essentials in Arabic,False,Free,3329,193,33,Beginner Level,3.5 hours,2017-05-31T23:16:00Z,Graphic Design
2710,1257870,Photoshop CC 2015 Top New Features,False,Free,1477,3,13,All Levels,39 mins,2017-06-26T19:37:58Z,Graphic Design
2719,1223336,Photoshop Essentials - Uma Introdução Detalhada,False,Free,800,39,24,Beginner Level,2.5 hours,2017-05-22T09:58:21Z,Graphic Design
2726,348116,Photoshop In-Depth: Master all of Photoshop's ...,False,Free,53851,1779,45,All Levels,4.5 hours,2014-11-30T04:22:11Z,Graphic Design
2895,611804,Primeros Pasos con Photoshop CC,False,Free,6429,654,31,Beginner Level,2.5 hours,2015-09-23T15:30:59Z,Graphic Design
2904,399938,Professional Logo Design in Adobe Illustrator,False,Free,44044,1563,45,All Levels,7.5 hours,2015-01-22T11:18:06Z,Graphic Design
2975,611370,"Quote Images for Pinterest, Facebook, & Instagram",False,Free,12103,576,18,Beginner Level,1 hour,2015-09-24T19:47:45Z,Graphic Design
3119,839536,Start Making Comics with Manga Studio 5 / Clip...,False,Free,5301,125,77,All Levels,6.5 hours,2016-06-21T02:49:47Z,Graphic Design
3541,1245392,Voxel 3D Model Creation Course,False,Free,1031,9,8,All Levels,39 mins,2017-06-08T22:46:39Z,Graphic Design

In [32]:
free_graphic.shape

(35, 11)

In [33]:
pd.concat([free_graphic, final_df], ignore_index=True)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,733878,Adobe Illustrator Course in Urdu Basics Level ...,False,Free,1433,57,8,Beginner Level,1 hour,2016-01-19T17:22:59Z,Graphic Design
1,723818,Adobe Indesign CC Başlangıç,False,Free,637,21,22,Beginner Level,2.5 hours,2016-01-14T18:52:21Z,Graphic Design
2,896742,Aprenda Modelagem 3D com o 123D Design,False,Free,334,26,27,Beginner Level,1 hour,2016-07-07T21:15:34Z,Graphic Design
3,1249378,AutoCAD Course - Learn Online AutoCAD in Urdu ...,False,Free,105,2,22,All Levels,2 hours,2017-06-13T17:32:48Z,Graphic Design
4,1261122,画像加工の初心者でも「１日」で初歩を覚えられる無料講座,False,Free,21,0,18,Beginner Level,1 hour,2017-06-22T15:01:32Z,Graphic Design
...,...,...,...,...,...,...,...,...,...,...,...
480,133968,Web Elements Design With Photoshop,True,45,5072,38,44,All Levels,5 hours,2014-10-21T19:18:12Z,Graphic Design
481,1131780,"Whiteboard Animation, Beginner To Expert - In ...",True,20,1343,25,16,All Levels,1 hour,2017-03-14T20:52:30Z,Graphic Design
482,1122306,Wordpress: Comment utiliser le thème FABLE,True,20,1,0,10,Beginner Level,39 mins,2017-03-07T16:53:27Z,Graphic Design
483,144222,"YOU can Draw, Shade and Paint a Mixed Media Gi...",True,30,1249,44,19,Beginner Level,3 hours,2014-01-28T02:30:26Z,Graphic Design
484,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

### 8. List out all the courses that are related with 'Python'.

In [34]:
df[df.course_title.str.contains('Python')]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
216,599504,Advanced Scalable Python Web Development Using...,True,120,1299,56,71,Intermediate Level,14 hours,2016-08-11T22:09:24Z,Web Development
777,47963,"Coding for Entrepreneurs: Learn Python, Django...",True,195,23412,799,251,All Levels,45 hours,2013-04-08T00:46:14Z,Web Development
814,631128,Complete Python Web Course: Build 8 Python Web...,True,110,7489,941,173,All Levels,16 hours,2015-11-08T20:57:35Z,Web Development
842,186096,"Core: A Web App Reference Guide for Django, Py...",True,195,2497,98,154,All Levels,26 hours,2014-05-29T00:58:43Z,Web Development
1400,394832,Fun and creative web engineering with Python a...,False,Free,10917,319,25,All Levels,2 hours,2015-06-09T19:51:50Z,Web Development
1932,1038538,Introduction to QGIS Python Programming,True,85,197,26,28,Beginner Level,3.5 hours,2016-12-22T00:11:22Z,Web Development
1969,902888,Investment Portfolio Analysis with Python,True,50,209,13,37,All Levels,7 hours,2016-07-13T21:40:32Z,Business Finance
2294,391546,Learn Python and Django: Payment Processing,True,70,17714,198,23,All Levels,3.5 hours,2015-02-09T15:37:56Z,Web Development
2295,1063722,Learn Python Django - A Hands-On Course,True,50,1339,21,18,Beginner Level,2 hours,2017-01-18T21:53:34Z,Web Development
2341,546848,Learn to code in Python and learn Adobe Photos...,True,50,1132,1,29,All Levels,2 hours,2015-07-08T00:15:12Z,Graphic Design
2906,368340,Professional Python Web Development Using Flask,True,120,3420,489,102,Beginner Level,14.5 hours,2015-03-04T00:10:36Z,Web Development
2908,1035940,Professional RESTful API Design using Python F...,True,120,578,25,36,Intermediate Level,4.5 hours,2017-01-11T21:15:25Z,Web Development
2929,270808,Projects in Django and Python,True,60,1764,53,28,All Levels,6.5 hours,2014-10-21T07:58:07Z,Web Development
2952,1170894,Python Algo Stock Trading: Automate Your Trading!,True,95,1165,21,41,Beginner Level,2.5 hours,2017-05-28T23:41:03Z,Business Finance
2953,1070886,Python Algo Trading: FX Trading with Oanda,True,200,453,42,33,Intermediate Level,3 hours,2017-03-14T00:39:45Z,Business Finance
2954,1196544,Python Algo Trading: Sentiment Trading with News,True,200,294,19,42,All Levels,7 hours,2017-04-28T16:41:44Z,Business Finance
2955,822444,Python and Django Full Stack Web Developer Boo...,True,200,11832,1883,191,All Levels,31.5 hours,2017-02-24T18:40:55Z,Web Development
2956,477702,Python for Beginners: Python Programming Langu...,True,150,6153,125,84,Beginner Level,5 hours,2015-06-14T18:18:57Z,Web Development
2957,1035472,Python for Finance: Investment Fundamentals & ...,True,195,3811,278,103,All Levels,6.5 hours,2017-03-30T22:17:09Z,Business Finance
2958,529828,Python for Trading & Investing,True,95,638,25,36,All Levels,5 hours,2015-06-17T22:23:31Z,Business Finance
2959,70640,Python Programming: Create an Digital Marketpl...,True,195,4198,145,161,All Levels,26 hours,2013-10-20T19:53:28Z,Web Development
2960,523312,Python Web Programming,True,100,1020,46,60,Beginner Level,6 hours,2015-07-01T21:46:36Z,Web Development
2962,1088656,Quantitative Trading Analysis with Python,True,50,256,17,49,All Levels,5.5 hours,2017-01-27T17:11:28Z,Business Finance
3013,970600,REST APIs with Flask and Python,True,110,5151,737,115,Intermediate Level,12.5 hours,2016-11-06T19:00:38Z,Web Development
3154,815482,Stock Technical Analysis with Python,True,50,409,35,46,All Levels,8 hours,2016-04-12T00:40:03Z,Business Finance
3272,938560,The Complete Ethical Hacking Course 2.0: Pytho...,True,195,7827,268,66,All Levels,11 hours,2016-09-26T15:08:29Z,Web Development
3460,76052,Try Django 1.9 | Build a Blog and Learn Python...,True,50,7407,172,147,All Levels,20 hours,2014-03-04T07:12:21Z,Web Development
3573,16646,Web Programming with Python,True,50,35267,217,53,All Levels,4 hours,2012-04-25T00:01:43Z,Web Development
3574,574082,"Web Scraping with Python, Ruby & import. io",True,75,973,50,46,All Levels,4.5 hours,2015-08-09T22:16:41Z,Web Development

In [35]:
df[df.course_title.str.contains('Python')].shape[0]

29

### 9. What are courses that published in year 2015 ?

In [36]:
df.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments

In [37]:
df.insert(10, 'year', pd.to_datetime(df.published_timestamp).dt.year)

In [38]:
df.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,year,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,2014,Musical Instruments

In [39]:
df[df.year == 2015]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,year,subject
10,591880,1 - Concepts of Statistics For Beginners Step ...,True,200,273,4,15,Beginner Level,31 mins,2015-08-30T22:48:34Z,2015,Business Finance
16,302450,10 Numbers Every Business Owner Should Know,True,20,13,1,9,All Levels,1 hour,2015-03-08T19:11:24Z,2015,Business Finance
19,384928,101 Blues riffs - learn how the harmonica supe...,True,200,1350,65,55,Intermediate Level,6.5 hours,2015-01-04T21:14:31Z,2015,Musical Instruments
23,550842,16 Guitar Chords to Jam With - (Beginner - Int...,True,20,1224,19,20,Beginner Level,1 hour,2015-07-10T19:53:56Z,2015,Musical Instruments
26,486240,2 Easy Steps To Investment And Avoiding Traps,True,20,828,1,20,All Levels,1 hour,2015-04-27T23:18:59Z,2015,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3675,551170,Your First Course on Piano,True,70,2002,34,33,Beginner Level,4 hours,2015-07-16T17:07:49Z,2015,Musical Instruments
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26T20:48:48Z,2015,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,2015,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,2015,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,2015,Web Development

In [40]:
df[df.year == 2015].shape[0]

1014

### 10. What are the Max. Number of Subscribers for Each Level of courses ?

In [41]:
df.groupby('level')['num_subscribers'].max().reset_index().sort_values('num_subscribers', ascending=False)

                level  num_subscribers
0          All Levels           268923
1      Beginner Level           161029
3  Intermediate Level            29167
2        Expert Level             5172